# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('multiplayer', models.BooleanField(default=False)),
                ('nb_players', models.IntegerField()),
                ('map_height', models.IntegerField()),
                ('map_width', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('turn_gold', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Node')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gold', models.IntegerField(default=3)),
                ('points', models.IntegerField(default=0)),
                ('turn_gold', models.IntegerField(default=3)),
                ('turn_buy', models.IntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=128, null=True)),
                ('mandatory', models.BooleanField(default=False, help_text='The type will be present in all games.')),
                ('start_number', models.IntegerField(default=10, help_text='Number of times this type can be bought in a game.')),
                ('end_game', models.BooleanField(default=False, help_text='The game ends when this type can no longer be bought.')),
                ('cost', models.IntegerField()),
                ('add_building', models.IntegerField(default=0)),
                ('add_prestige', models.IntegerField(default=0)),
                ('add_gold', models.IntegerField(default=0)),
                ('add_node_gold', models.IntegerField(default=0)),
                ('add_points', models.IntegerField(default=0)),
                ('add_buy', models.IntegerField(default=0)),
                ('special_effects', models.CharField(max_length=128, null=True)),
                ('need_slot', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('B', 'Building'), ('P', 'Prestige')], default='B', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Type'),
        ),
        migrations.AddField(
            model_name='node',
            name='places',
            field=models.ManyToManyField(through='game.Place', to='game.Type'),
        ),
        migrations.AddField(
            model_name='node',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
        ),
        migrations.AddField(
            model_name='deck',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='game.Game'),
        ),
        migrations.AddField(
            model_name='deck',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Type'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('game', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='player',
            index_together=set([('game', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set([('game', 'type')]),
        ),
        migrations.AlterIndexTogether(
            name='deck',
            index_together=set([('game', 'type')]),
        ),
    ]
