# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_type_need_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='add_points',
            field=models.IntegerField(default=0),
        ),
    ]
